name: "Terraform Format"

on:
  push:
    branches:
    - '*'
    - '!main'

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  WORKING_DIRECTORY: "."

jobs:
  terraform:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -recursive ${{ env.WORKING_DIRECTORY }}

    - name: git add
      run: git add ${{ env.WORKING_DIRECTORY }}

    - name: git commit
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git commit -m "Terraform Format"

    - name: git push
      run: git push

    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = "Terraform Format"
          const body = "Terraform Format"
          const head = "terraform-format"
          const base = "main"
          const res = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            head: head,
            base: base
          })
          console.log(res.data.html_url)