name: "Terraform Format"

on:
  push:
    branches:
    - '*' # 모든 브랜치에 대한 푸시 이벤트를 감지합니다.
    - '!main' # main 브랜치는 제외합니다.

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}" # Terraform API 토큰
  WORKING_DIRECTORY: "." # 작업 디렉토리 설정

jobs:
  terraform:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      actions: write


    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init # Terraform 초기화

    - name: Terraform Format
      run: | 
        terraform fmt -recursive ${{ env.WORKING_DIRECTORY }} > format.diff # Terraform 포맷팅
        if [ -s format.diff ]; then
        echo "TERRAFORM_FORMAT_DIFF=true" >> $GITHUB_ENV
        fi

    - name: git add and commit
      run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add ${{ env.WORKING_DIRECTORY }}
          git commit -m "Terraform Format"
      if: env.TERRAFORM_FORMAT_DIFF == 'true'

    - name: git push
      run: git push
      if: env.TERRAFORM_FORMAT_DIFF == 'true'

    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: 'Terraform Format',
            owner,
            repo,
            head: '${{ github.ref_name}}',
            base: 'main',
            body: [
              'Terraform Format',
              'This PR is created by GitHub Actions'
            ].join('\n')
          });
          github.rest.issues.addLabels({
            owner,
            repo,
            issue_number: result.data.number,
            labels: ['feature','automated pr','terraform format']
          })
          })