name: "Terraform Format"

on:
  push:
    branches:
    - '*'
    - '!main'

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  WORKING_DIRECTORY: "."

jobs:
  terraform:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -recursive ${{ env.WORKING_DIRECTORY }}

    - name: git add
      run: git add ${{ env.WORKING_DIRECTORY }}

    - name: git commit
      run: git commit -m "Terraform Format" ${{ env.WORKING_DIRECTORY }}

    - name: git push
      run: git push

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Terraform Format"
        title: "Terraform Format"
        body: "Terraform Format"
        branch: "terraform-format"
        base: "main"
        labels: "terraform-format"
        draft: false

