name: "Terraform Format"

on:
  push:
    branches:
    - '*'
    - '!main'

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  WORKING_DIRECTORY: "."

jobs:
  terraform:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -recursive ${{ env.WORKING_DIRECTORY }}

    - name: git Commit
      uses: actions/github-script@v6
      id: commit
      with:
        script: |
          const output = `terraform fmt -recursive ${process.env.WORKING_DIRECTORY}`;
          console.log(output);
          const result = exec(output);
          console.log(result);
          return result;

    - name: git Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
